# 头部菜单，title: link
menu:
  Whoami: /posts/2018/08/AboutMe/
  Github: https://github.com/Beacon1096
  Twitter: https://twitter.com/Beacon1096

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: true

# 默认音乐
mp3: 
#  - https://beacon1096-github-io-1258087381.cos.ap-chengdu.myqcloud.com/site/default-music.mp3
   - http://music.163.com/song/media/outer/url?id=1332904662
# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: https://beacon1096-github-io-1258087381.cos.ap-chengdu.myqcloud.com/site/welcome-cover.jpg

# 默认文章封面图
cover: https://beacon1096-github-io-1258087381.cos.ap-chengdu.myqcloud.com/site/default-cover.jpg

# 是否关闭默认滚动条
scrollbar: false

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
#gitalk:
    # 是否自动展开评论框
#    autoExpand: false
    # 应用编号
#    clientID: ''
    # 应用秘钥
#    clientSecret: ''
    # issue仓库名
#    repo: ''
    # Github名
#    owner: ''
    # Github名
#    admin: ['']
    # Ensure uniqueness and length less than 50
#    id: location.pathname
    # Facebook-like distraction free mode
#    distractionFreeMode: false

# 网站关键字
keywords: Beacon1096

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: https://beacon1096-github-io-1258087381.cos.ap-chengdu.myqcloud.com/site/favicon.png

# rss文件
rss: atom.xml
